spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # for string input validation in payload
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

# Server properties
server:
  port: 8080

build:
  info: 1.0
